#!/bin/bash
set -e

PROG_NAME=$1

if [[ ! -n $PROG_NAME ]]; then
  echo "Usage: $0 [program_name]"
  exit 1
fi

CURRENT=$(dirname $0)

if [[ -f "$CURRENT/src/_$PROG_NAME" ]]; then
  echo "already exists $PROG_NAME completion scripts"
  exit 1
fi

cp "$CURRENT/src/__template" "$CURRENT/src/_$PROG_NAME"
sed -i "s/\$BIN/$PROG_NAME/g" "$CURRENT/src/_$PROG_NAME"

$EDITOR "$CURRENT/src/_$PROG_NAME"
